### ISSUE TITLE
平台登录后，界面右侧消息栏不能关闭

### ISSUE THREAD

**Issue by lionbrother** [keep2zero/smartlant#11]
平台登录后，界面右侧消息栏不能关闭（点击铃铛图标不能关闭，点击用户名处，菜单被消息栏遮挡），如图：
![image](https://user-images.githubusercontent.com/51153936/58541935-1fcb4600-822f-11e9-98b4-8a4b62da43b7.png)

**Comment by lionbrother** [comment]
点击右上角铃铛图标，并不能关闭

**Comment by keep2zero** [comment]
造成这个原因是: 设定了, 手动关闭功能
