### ISSUE TITLE
小程序端展示顺序问题：

### ISSUE THREAD

**Issue by lionriverman** [keep2zero/smartlant#110]
平台最新展示的房源，在小程序端不是展示在最前面。
例如新增一个3层、每层5间的房源。房号依次是101、102.....105、201...205、301、302、...、305
如果平台端先展示305房间，最后再展示201房间，期望是201再最前面。
现状是305在最前面。
即：现状是平台端新增房源的次序，不是平台端做展示操作的次序。
参考#91问题。

**Comment by willculture** [comment]
这个不一定这样的, 因为小程序端是对所有房东和企业的, 这个展示顺序, 可能不能针对某一个房东或者企业来做

**Comment by willculture** [comment]
目前按最新增的来做的, 以后可以参考其他平台, 或者我们加入推荐操作等都可以

**Comment by lionriverman** [comment]
没改。待讨论
