### ISSUE TITLE
小程序端，点“查看更多”进入列表，选择项的描述问题

### ISSUE THREAD

**Issue by lionriverman** [keep2zero/smartlant#119]
如图，下拉选择项后，图中蓝色字样的“户型”、“方式”、“租金”、“区域”，
是否应该改成“全部”或者“不限”
![微信图片_201906101057141](https://user-images.githubusercontent.com/51182693/59169920-deac2d80-8b6e-11e9-8194-955608ebb146.jpg)
![微信图片_201906101057142](https://user-images.githubusercontent.com/51182693/59169922-df44c400-8b6e-11e9-80ea-33266b09ca76.jpg)
![微信图片_201906101057143](https://user-images.githubusercontent.com/51182693/59169923-df44c400-8b6e-11e9-9343-e752c62f58e7.jpg)
![微信图片_20190610110236](https://user-images.githubusercontent.com/51182693/59170048-5712ee80-8b6f-11e9-83cb-7448e28c0532.jpg)

**Comment by keep2zero** [comment]
我是為了區分改成這個的， 全部是都是全部字樣， 不好區分

**Comment by lionriverman** [comment]
参考贝壳找房，是同样处理方式。问题关闭
