### ISSUE TITLE
“房源列表”里，对列表中看得到的单套类型的房源，点击“编辑”，出现已删除提示。

### ISSUE THREAD

**Issue by lionriverman** [keep2zero/smartlant#120]
如图。
如果已删除了，列表中不应显示出来
![image](https://user-images.githubusercontent.com/51182693/59170589-ede0aa80-8b71-11e9-8097-8b8d83b460c8.png)

**Comment by keep2zero** [comment]
這是你之前異常添加的數據， 我給你刪除把

**Comment by lionriverman** [comment]
属于调试数据。
