### ISSUE TITLE
小程序首页，往上拖动房源时，难以点击“查看更多”

### ISSUE THREAD

**Issue by lionbrother** [keep2zero/smartlant#13]
“查看更多”被遮挡，往上拖仍会回到底部被遮挡

**Comment by keep2zero** [comment]
已修复完成

**Comment by willculture** [comment]
苹果手机上无法操作

**Comment by lionriverman** [comment]
新版本可以拖动看到“查看更多”，但该按钮底部有部分被遮挡不能上移出来。如图：
![41559354422_ pic](https://user-images.githubusercontent.com/51182693/58742361-f7259500-8456-11e9-9d94-e0f68a578c5e.jpg)

**Comment by lionriverman** [comment]
已验证。
