### ISSUE TITLE
企业资料编辑的某些栏目缺少控件

### ISSUE THREAD

**Issue by lionbrother** [keep2zero/smartlant#14]
路径：功能-认证管理-企业资料
问题：企业资料编辑界面，“成立日期”没有日期控件，“执照扫描件”没有上传控件。另外建议对注册资金等数字型字段，做输入合法性检查。

**Comment by keep2zero** [comment]
已加入控件支持

**Comment by lionriverman** [comment]
注册资金目前可以输入负数，需检查控制。

**Comment by lionriverman** [comment]
目前版本，”企业资料“菜单已关闭，不能操作。
