### ISSUE TITLE
对类型为“单套（signle）”的房源编辑时，编辑界面是空白的

### ISSUE THREAD

**Issue by lionriverman** [keep2zero/smartlant#22]
如图：
![屏幕快照 2019-05-30 上午11 17 24](https://user-images.githubusercontent.com/51182693/58606131-d9c4bf80-82cc-11e9-9682-5f164f195175.png)

**Comment by lionriverman** [comment]
问题仍在存在

**Comment by lionriverman** [comment]
目前版本是对单套的点击“编辑”后，没有响应

**Comment by keep2zero** [comment]
网络请求慢, 会造成这样, 已加入了加载方式.

**Comment by lionriverman** [comment]
对单套的，点编辑，出现一段时间的加载图标，然后没有编辑界面出现。

**Comment by willculture** [comment]
之前调整过数据库, 这个数据变成了有异常, 已修复该问题的, 请将该数据删除后重新添加
