### ISSUE TITLE
“房源房间”里展示与空置两个切换按钮的名称有歧义

### ISSUE THREAD

**Issue by lionriverman** [keep2zero/smartlant#29]
“未展示”、“空置中”，切换状态后，状态开关颜色变了，但文字仍是“未展示”，“空置中”，文字描述要更换，避免误解。
如图红框处：
![屏幕快照 2019-05-30 下午3 40 05](https://user-images.githubusercontent.com/51182693/58617163-063f0280-82f2-11e9-9003-7a36bc11040d.png)

**Comment by keep2zero** [comment]
已改为展示状态, 出租状态, 未处理状态, 颜色为灰色
