### ISSUE TITLE
房源收藏功能无效。

### ISSUE THREAD

**Issue by cjwboy** [keep2zero/smartlant#3]

**Comment by keep2zero** [comment]
已解决, 缓存过的账号, 未正确返回相关的错误信息, 需要转向到重新登录

**Comment by lionriverman** [comment]
进入房源界面时，收藏按钮先显示“已收藏”，再刷新为“收藏”。不应显示已收藏。
另建议收藏后，收藏按钮用红色表示，以和未收藏区别。

**Comment by keep2zero** [comment]
已区别

**Comment by lionriverman** [comment]
对没有收藏的房源，进入房源界面时，仍会先显示“已收藏”文字及红色图标，再显示“收藏”及黑色图标。
收藏这里，不应先显示不正确的状态

**Comment by willculture** [comment]
数据需要加载之后才会显示正确的状态, 目前已调整, 数据未获取时, 按钮不展示
