### ISSUE TITLE
平台端，全部消息阅读完毕后，消息图标上仍有红点提示，如图：

### ISSUE THREAD

**Issue by lionriverman** [keep2zero/smartlant#45]
![屏幕快照 2019-05-31 上午9 43 12](https://user-images.githubusercontent.com/51182693/58675926-fe7e6d00-8388-11e9-9838-e90293e3a645.png)

**Comment by keep2zero** [comment]
这个，我方便调试，把实时获取消息的停掉了

**Comment by lionriverman** [comment]
同#101问题
