### ISSUE TITLE
“财务管理-财务统计”中，应增加房源信息栏，目前的各栏目看不出是哪个房源的费用

### ISSUE THREAD

**Issue by lionriverman** [keep2zero/smartlant#51]
现状如图：
![屏幕快照 2019-05-31 上午11 28 17](https://user-images.githubusercontent.com/51182693/58679768-7a7fb180-8397-11e9-89ef-62cd5d5c4eb6.png)

**Comment by willculture** [comment]
已加入该功能, 但是老数据的话是没有该信息. 这里之前只做订单使用
