### ISSUE TITLE
“租约管理-办理出租”列表里，房源图片加载失败。而图片已在“房源列表-房源房间”上传。见截图：

### ISSUE THREAD

**Issue by lionriverman** [keep2zero/smartlant#59]
例如下面三张图里的102房间：
![屏幕快照 2019-05-31 下午4 25 37](https://user-images.githubusercontent.com/51182693/58692235-c561ef00-83c0-11e9-9de6-d5ac265aeec8.png)
![屏幕快照 2019-05-31 下午4 21 40](https://user-images.githubusercontent.com/51182693/58692265-d874bf00-83c0-11e9-8bab-0f4f811f49c1.png)
![屏幕快照 2019-05-31 下午4 21 10](https://user-images.githubusercontent.com/51182693/58692143-8fbd0600-83c0-11e9-9935-031f75b7fd4b.png)

**Comment by keep2zero** [comment]
这里有可能是网络问题, 图片加载超时

**Comment by lionriverman** [comment]
列表里的图片仍然加载不到，例如其中一个图片地址是：
http://172.20.10.103:3000/file/image/show/5cef882ebbf2ff82d5b9b24a

在“查看租约”按钮后，“房源房间”界面的图片可以加载，例如其中一个图片地址是：
https://api.smartlant.com/file/image/show/5cef870bbbf2ff82d5b9b23e

**Comment by lionriverman** [comment]
图片目前都在https://api.smartlant.com/file/image/show/，可以加载图片
