### ISSUE TITLE
小程序端图片展示，需要整齐。对比例不同的原始图片，可截取长边或者对短边两侧留白处理。

### ISSUE THREAD

**Issue by lionriverman** [keep2zero/smartlant#66]
下面是“智慧新民居”和“小蓝汇租”现版本的对比：
![11559354419_ pic](https://user-images.githubusercontent.com/51182693/58742269-1839b600-8456-11e9-946d-8ae850761bb5.jpg)
![21559354420_ pic](https://user-images.githubusercontent.com/51182693/58742270-18d24c80-8456-11e9-971e-e16c957ca534.jpg)

**Comment by lionriverman** [comment]
小程序端的展示图显示方式，庄总建议参考“智慧新民居”的展示图片大小、比例。

**Comment by keep2zero** [comment]
已调整统一比例

**Comment by lionriverman** [comment]
建议参考“智慧新民居”的图片比例，见前面的附图。

**Comment by willculture** [comment]
已调整
