### ISSUE TITLE
小程序端，房源来源以及出租方式的显示问题，如图

### ISSUE THREAD

**Issue by lionriverman** [keep2zero/smartlant#67]
如图，
1、该房源是某企业整栋楼其中的一个房间，这里显示“个人房源”是否合适？
2、图中圈起处，是个灰框，没有文字。参考“智慧新民居”，这里显示出租方式。
![WechatIMG5](https://user-images.githubusercontent.com/51182693/58742909-e6771e00-845a-11e9-93af-c0510804860e.jpeg)

**Comment by keep2zero** [comment]
你这个是5/31创建的, 当时是个人房东角色创建的(目前有多个角色登录方式), 空白灰色处已修复, 字段拼写问题
