### ISSUE TITLE
“房源列表-完善楼层-房源楼层”里，“增加费用”以及“增加配套”应更改描述

### ISSUE THREAD

**Issue by lionriverman** [keep2zero/smartlant#73]
实际上点击后，是可以增加或加少费用项、配套项的，按钮的文字描述应更改，改为“增减”或“编辑”或“修改”，如图：
![屏幕快照 2019-06-01 下午2 18 28](https://user-images.githubusercontent.com/51182693/58744728-e0903580-8478-11e9-80c7-739c3e33601b.png)

**Comment by willculture** [comment]
已改为编辑
