### ISSUE TITLE
数据变更后，未及时同步，在小程序端，同一房间出现两个不同的租金。水电等费用也没有同步更新

### ISSUE THREAD

**Issue by lionriverman** [keep2zero/smartlant#74]
1、该房间发布时，是1020元，后来在房源列表的完善楼层里，改为1200元，但小程序端看到两个不同租金。
2、在在房源列表的完善楼层里，修改电费为1.3元，但该房间仍显示1元。

对于平台操作者来说，他在任何界面对某房间的数据变更，在所有涉及该房间的地方，数据都要自动同步变化。不能把数据同步的工作交给平台操作者手工到各涉及界面去修改，要自动同步。

见如下两张图：
![71559370664_ pic](https://user-images.githubusercontent.com/51182693/58744958-809b8e00-847c-11e9-8355-d2d35977d332.jpg)
![81559370665_ pic](https://user-images.githubusercontent.com/51182693/58744959-809b8e00-847c-11e9-8622-23ef395d9904.jpg)

**Comment by keep2zero** [comment]
租约的租金, 是不能和房间的租金化为等号的. 不同时间出租的同一房间, 他们的租金都是不同的. 以租约为准的, 就像签订合同时, 租金是可以更改的, 所以出租的时候, 以租约为准
