### ISSUE TITLE
租户账单界面里，目前只能看到局部的日期信息，建议每个列表项用多行显示，展示必须的信息

### ISSUE THREAD

**Issue by lionriverman** [keep2zero/smartlant#86]
如图，也要显示房源等信息
![WechatIMG9](https://user-images.githubusercontent.com/51182693/58746806-31ae2280-8495-11e9-92ba-d96336a68a26.jpeg)

**Comment by willculture** [comment]
已调整为多行展示

**Comment by lionriverman** [comment]
目前年月日的间隔符，两个日期的间隔符，都是“-”符合。建议区分，让用户看上去清晰

**Comment by willculture** [comment]
用"至"做间隔了

**Comment by lionriverman** [comment]
没有“至”，还都是“-”，如图
![image](https://user-images.githubusercontent.com/51182693/59400340-b66c3b00-8dc9-11e9-9df2-de7b4b0ff0af.png)
