### ISSUE TITLE
租户账单信息列表里，已支付的项目建议绿色或其他颜色显示，与未支付的区分

### ISSUE THREAD

**Issue by lionriverman** [keep2zero/smartlant#87]
如图：
![WechatIMG10](https://user-images.githubusercontent.com/51182693/58746872-08da5d00-8496-11e9-8ebf-7247d9801fbd.jpeg)

**Comment by keep2zero** [comment]
以分类形式展示

**Comment by lionriverman** [comment]
已验证，分类展示。
