### ISSUE TITLE
“房源列表-房源房间”里，对不存在的功能房的数量采用不同方式编辑后，在小程序端展现的描述不一致，需要统一的描述方式。如图示例：

### ISSUE THREAD

**Issue by lionriverman** [keep2zero/smartlant#93]
如以下四张图：
平台端填0厅，小程序端表现为0厅；平台端空白不填，小程序端表现为null厅。
小程序端应该统一描述方式，比如统一为0厅，或者不出现厅的数量描述。
平台端，可以写0，也可以不填，也需要统一控制填写方式。
![0](https://user-images.githubusercontent.com/51182693/58863445-73350c80-86e5-11e9-9ff9-3d90c4499b8c.jpg)
![微信图片_20190604161907](https://user-images.githubusercontent.com/51182693/58863515-87790980-86e5-11e9-83e1-18deeaa9f4f9.jpg)

![null](https://user-images.githubusercontent.com/51182693/58863539-92339e80-86e5-11e9-9139-31e0d27aed84.jpg)
![微信图片_201906041619071](https://user-images.githubusercontent.com/51182693/58863561-9cee3380-86e5-11e9-9f46-e76a7180ba87.jpg)

**Comment by willculture** [comment]
统一为0
