### ISSUE TITLE
小程序端，按关键字搜索房源，不起作用

### ISSUE THREAD

**Issue by lionriverman** [keep2zero/smartlant#98]
如以下两张图。
图一是房源列表，有地址为同乐村的若干房源
图二是按“同乐”关键字搜索，没有搜到数据。
![微信图片_20190605120847](https://user-images.githubusercontent.com/51182693/58929677-b8f7e080-878a-11e9-8d8c-970e3dfbf30b.jpg)
![微信图片_201906051208471](https://user-images.githubusercontent.com/51182693/58929687-c01eee80-878a-11e9-94d9-d73d63cd45e8.jpg)

**Comment by willculture** [comment]
已加入, 关键词关联地址
